# Generated by Django 5.1.4 on 2025-02-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_faq_created_at_faq_is_answered_faq_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
