# Generated by Django 5.1.4 on 2025-02-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_faq_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
    ]
