# Generated by Django 5.1.4 on 2025-02-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_faq_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
