# Generated by Django 4.2.16 on 2025-04-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_email_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSkillsCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_certifications', to='users.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
