# Generated by Django 4.2.16 on 2025-04-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_city_profile_country_profile_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileskillscertifications',
            name='certifications',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.profileskillscertifications')),
            ],
        ),
    ]
