# Generated by Django 4.2.16 on 2025-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_jobapplication_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Ongoing'), ('placed', 'Placed')], default='applied', max_length=20),
        ),
    ]
