# Generated by Django 4.2.16 on 2025-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_type',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], default='Fresher', max_length=50),
        ),
    ]
