# Generated by Django 4.2.16 on 2025-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_date_to_apply', models.DateField()),
                ('eligibility', models.TextField()),
                ('job_description', models.TextField()),
                ('company_website', models.URLField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tpo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
