# Generated by Django 4.2.16 on 2025-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_profiles/'),
        ),
    ]
