# Generated by Django 4.2.16 on 2025-04-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0003_alumni_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tpo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tpo.tpo'),
        ),
    ]
