# Generated by Django 4.2.16 on 2025-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0006_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
